#!/bin/bash

  #******************************************# 
  #                                          # 
  #		   snapshot_dir              #
  #	      written by JB Braendel         #
  #		November 13, 2012            #
  #                                          #
  #	    Take snapshot of directory       #
  #******************************************# 

 

# ---------------------------------#
# snapdir ()                       #
# echo snapshot of directory       #
# Parameter: $target_directory     #
# Parameter: $echo_prefix          #
# ---------------------------------#
snapdir () {
    # $1 should be a proper directory
    if [ -z "$1" ]; then
	return 0;
    elif [ ! -d "$1" ]; then
	return 0;
    fi

    # print each file/directory
    for file in `ls ${1} | xargs -0 | sed -r 's/[ \t]+//g'`; do
	if [ -d "${1}/${file}" ]; then
	    echo " ${2}$file/"
	    snapdir "${1}/${file}" "${2}  "
	else
	    echo " ${2}$file"
	fi
    done
}


target_dir=${1:-.}
snapdir "$target_dir"
